name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Author and Last Commit
        run: |
          AUTHOR=$(git log -1 --pretty=format:"%an")
          LAST_COMMIT=$(git log -1 --pretty=format:"%h %s")
          echo "Author: $AUTHOR"
          echo "Last Commit: $LAST_COMMIT"

      - name: Get Changes
        run: |
          CHANGES=$(git diff --name-only HEAD...origin/main)
          echo "Changes:"
          echo "$CHANGES"

      - name: Hello World
        run: echo "Hello World"
