name: hello-world

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print Hello World
        run: |
          echo "Hello World!"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Last Commit: ${{ github.event.pull_request.head.sha }}"
          echo "Changes between last commit and default branch:"
          git --no-pager diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
